### ISSUE TITLE
Traceback Issue: line 147: apiUrl = config['main']['API_URL']

### ISSUE THREAD

**Issue by paeore** [mikeymakesit/DownloadMyThings#1]
Hi Mikey

I am trying to run this tool on my windows 10 machine using python version 3.6.5 and am receiving this following error when running:

`Traceback (most recent call last):
  File "dlthings", line 147, in <module>
    apiUrl = config['main']['API_URL']
  File "C:\Python36\lib\configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'main'
`

Any idea how i can fix this?

Many thanks

paeore

**Comment by mikeymakesit** [comment]
It seems you haven't created a config file with a "main" section.

On line 12 of _dlthings_ you'll see a global variable that defines the name of your config file, by default it's './config'.  Your config file needs to have a section called "main" with the following settings:

> [main]
> API_URL         = https://api.thingiverse.com
> MANIFEST_FILE   = things.json
> THING_FILE      = thingdata.json
> APP_TOKEN       = PUT_YOURS_HERE

You can get your app token using the method I described in the README for this project.

**Comment by paeore** [comment]
Thanks for the reply

Yes, I generated an app token using the method you described in the README.

Here's the contents of my "main" file:

For security, I replaced my _actual_ alphanumeric App Token below with "MY_OWN_UNIQUE_APP_TOKEN"

> [main]
>API_URL         = https://api.thingiverse.com
>MANIFEST_FILE   = things.json
>THING_FILE      = thingdata.json
>APP_TOKEN       = MY_OWN_UNIQUE_APP_TOKEN

**Comment by mikeymakesit** [comment]
Does your config filename match what's on line 12 in your dlthings script?  I don't know if the "./filename" separator works on Windows.  You might consider first making sure your configured config filename and actual filename match, then update line 12 in dlthings to remove the "./" from the file location.  I haven't used Python in Windows so I'm not sure how to provide the path to a file properly.

I was able to duplicate your traceback by changing the name of my config file to something different from what's set on line 12 in the dlthings script.

**Comment by paeore** [comment]
Your dlthings code was pointing to:
`CONFIGFILE   = './config'`
but changing this to `./config.example` as per your code and it ran perfect. Thank you! 😄 👍 

Is there a way I am able to tweak the code so I can download all my liked files?

Thanks again!

**Comment by mikeymakesit** [comment]
Congrats on getting it working.

You can definitely tweak this project to download all the Things you've liked.  You'll need to read through [the API docs](https://www.thingiverse.com/developers/rest-api-reference).  A direct approach would be getting all your likes, then downloading the things in the returned array.  Best of luck!
